### ISSUE TITLE
License of code

### ISSUE THREAD

**Issue by audricschiltknecht** [jkeiser/iter#1]
Hello,
I'd be interested in using this module in one of my projects, but there is no license mentioned in your code.
Do you mind clarifying the license of your code (proprietary, open-source/libre)?

Thanks a lot!

**Comment by jkeiser** [comment]
I went ahead and added the MIT license. I'm surprised and tickled that someone is using it!

**Comment by jkeiser** [comment]
Resolving, but please reopen if you need a different license to use it. I have no desire to restrict the use of this code.
